# Generated by Django 3.1.7 on 2021-03-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210308_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimony',
            field=models.TextField(null=True),
        ),
    ]
